# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-27 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('success', models.IntegerField()),
                ('failed', models.IntegerField()),
            ],
            options={
                'verbose_name': '\u7ed3\u679c\u56fe\u8868',
                'verbose_name_plural': '\u7ed3\u679c\u56fe\u8868',
            },
        ),
    ]
