# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-29 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartconfig',
            name='class_name',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chartconfig',
            name='function_name',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
