# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-04 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTaskConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '\u5b9a\u65f6\u4efb\u52a1',
                'verbose_name_plural': '\u5b9a\u65f6\u4efb\u52a1',
            },
        ),
    ]
