# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-08 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetask', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanTastConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('plan_type', models.CharField(choices=[('S', '\u6bcf\u9694\u591a\u5c11\u5c0f\u65f6'), ('M', '\u6bcf\u5468\u4e00\u6b21'), ('L', '\u6bcf\u6708\u4e00\u6b21')], max_length=256)),
            ],
            options={
                'verbose_name': '\u8ba1\u5212\u4efb\u52a1',
                'verbose_name_plural': '\u8ba1\u5212\u4efb\u52a1',
            },
        ),
    ]
