# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-08 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetask', '0002_plantastconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanInfoConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': '\u7c7b\u578b\u4fe1\u606f\u914d\u7f6e',
                'verbose_name_plural': '\u7c7b\u578b\u4fe1\u606f\u914d\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='PlanTypeConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': '\u8ba1\u5212\u7c7b\u578b\u914d\u7f6e',
                'verbose_name_plural': '\u8ba1\u5212\u7c7b\u578b\u914d\u7f6e',
            },
        ),
        migrations.AlterField(
            model_name='plantastconfig',
            name='plan_type',
            field=models.ForeignKey(max_length=256, on_delete=django.db.models.deletion.CASCADE, to='timetask.PlanTypeConfig'),
        ),
        migrations.AddField(
            model_name='planinfoconfig',
            name='name',
            field=models.ForeignKey(max_length=256, on_delete=django.db.models.deletion.CASCADE, to='timetask.PlanTypeConfig'),
        ),
        migrations.AddField(
            model_name='plantastconfig',
            name='plan_info',
            field=models.ForeignKey(default=1, max_length=256, on_delete=django.db.models.deletion.CASCADE, to='timetask.PlanInfoConfig'),
            preserve_default=False,
        ),
    ]
