# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-08 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetask', '0003_auto_20180108_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planinfoconfig',
            name='info',
        ),
        migrations.AddField(
            model_name='planinfoconfig',
            name='plan_type',
            field=models.ForeignKey(default=1, max_length=256, on_delete=django.db.models.deletion.CASCADE, to='timetask.PlanTypeConfig'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planinfoconfig',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
