# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-08 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetask', '0004_auto_20180108_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planinfoconfig',
            name='name',
            field=models.CharField(max_length=256, verbose_name='\u5177\u4f53\u6267\u884c\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='planinfoconfig',
            name='plan_type',
            field=models.ForeignKey(max_length=256, on_delete=django.db.models.deletion.CASCADE, to='timetask.PlanTypeConfig', verbose_name='\u4efb\u52a1\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='plantastconfig',
            name='plan_info',
            field=models.ForeignKey(max_length=256, on_delete=django.db.models.deletion.CASCADE, to='timetask.PlanInfoConfig', verbose_name='\u5177\u4f53\u6267\u884c\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='plantastconfig',
            name='plan_type',
            field=models.ForeignKey(max_length=256, on_delete=django.db.models.deletion.CASCADE, to='timetask.PlanTypeConfig', verbose_name='\u4efb\u52a1\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='plantypeconfig',
            name='name',
            field=models.CharField(max_length=256, verbose_name='\u4efb\u52a1\u7c7b\u578b'),
        ),
    ]
