# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-08 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_delete_chartconfig'),
        ('timetask', '0006_auto_20180108_1702'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlanInfoConfig',
            new_name='PlanTimeConfig',
        ),
        migrations.AddField(
            model_name='plantastconfig',
            name='plan_time',
            field=models.ForeignKey(default=1, max_length=256, on_delete=django.db.models.deletion.CASCADE, to='timetask.PlanTimeConfig', verbose_name='\u5177\u4f53\u6267\u884c\u65e5\u671f'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='plantastconfig',
            name='plan_info',
        ),
        migrations.AddField(
            model_name='plantastconfig',
            name='plan_info',
            field=models.ManyToManyField(to='service.ProjectConfig', verbose_name='\u6570\u636e\u5217\u8868'),
        ),
    ]
