# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-08 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_delete_chartconfig'),
        ('timetask', '0008_auto_20180108_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetaskconfig',
            name='name',
            field=models.CharField(default=1, max_length=256, verbose_name='\u4efb\u52a1\u540d\u79f0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetaskconfig',
            name='plan_info',
            field=models.ManyToManyField(to='service.ProjectConfig', verbose_name='\u81ea\u52a8\u5316\u9879\u76ee'),
        ),
        migrations.AddField(
            model_name='timetaskconfig',
            name='plan_time',
            field=models.ForeignKey(default=1, max_length=256, on_delete=django.db.models.deletion.CASCADE, to='timetask.PlanTimeConfig', verbose_name='\u5177\u4f53\u6267\u884c\u65e5\u671f'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetaskconfig',
            name='plan_type',
            field=models.ForeignKey(default=1, max_length=256, on_delete=django.db.models.deletion.CASCADE, to='timetask.PlanTypeConfig', verbose_name='\u4efb\u52a1\u7c7b\u578b'),
            preserve_default=False,
        ),
    ]
