# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetask', '0009_auto_20180108_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantastconfig',
            name='project_name',
            field=models.CharField(choices=[('service', 'Service'), ('api', 'Api')], default=1, max_length=256, verbose_name='\u6240\u5c5e\u9879\u76ee'),
            preserve_default=False,
        ),
    ]
