# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-12 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetask', '0011_auto_20180112_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totalprojects',
            old_name='name',
            new_name='project_name',
        ),
        migrations.RenameField(
            model_name='totalprojects',
            old_name='type',
            new_name='project_type',
        ),
    ]
