# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-15 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetask', '0014_remove_plantastconfig_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantastconfig',
            name='name',
            field=models.CharField(max_length=256, verbose_name='\u4efb\u52a1\u540d\u79f0(\u4e0d\u652f\u6301\u4e2d\u6587)'),
        ),
    ]
